version: "3.8"

services:
  stg-everestvacation-fe:
    container_name: everest-frontend
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://staging-api.everestnepaltours.com
    restart: always
    networks:
      - shared-network

  stg-everestvacation-be:
    container_name: everest-backend
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - ./server/.env
    restart: always
    networks:
      - shared-network
networks:
  shared-network:
    external: true