
POST http://localhost:4000/comment/
Content-Type: application/json

{
  "response": "sad",
  "comment": "The weather was bad and the trip was delayed.",
  "packageTourName": "Annapurna Circuit Trek"
}

###
GET http://localhost:4000/comment/


###
GET http://localhost:4000/comment/by-package/Annapurna Circuit Trek