name: build

on:
  push:
    - staging

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Client CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
        # frontend
        docker build \
          -t ghcr.io/${{ github.repository_owner }}/stg-everestvacation-fe:${{ env.IMAGE_TAG }} -f client/Dockerfile client

        # backend
        docker build \
          -t ghcr.io/${{ github.repository_owner }}/stg-everestvacation-be:${{ env.IMAGE_TAG }} \
          -f server/Dockerfile \
          server
      
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/stg-everestvacation-fe:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/stg-everestvacation-be:${{ env.IMAGE_TAG }}